# Generated by Django 4.1.2 on 2022-10-28 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_users_profile_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
