# Generated by Django 4.1.3 on 2022-11-05 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_bookcopy_owner_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcopy',
            name='owner_id',
        ),
        migrations.AddField(
            model_name='bookcopy',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.users'),
        ),
    ]
