# Generated by Django 4.1.3 on 2022-11-10 05:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_bookcopy_owner_id_bookcopy_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
