# Generated by Django 4.1.2 on 2022-11-10 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_listing_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.TextField(default='Author Not Found'),
        ),
    ]
