# Generated by Django 4.1.3 on 2022-11-29 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_likes'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='likes',
            table='Likes',
        ),
    ]
