# Generated by Django 4.1.3 on 2022-11-29 22:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_likes_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
